// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgDkG1aLKvH2WfnfCKKWp7Ir9lPigEXAo',
    appId: '1:853922079394:web:7262f9f09710bcd3b2edfb',
    messagingSenderId: '853922079394',
    projectId: 'chatly-861ab',
    authDomain: 'chatly-861ab.firebaseapp.com',
    storageBucket: 'chatly-861ab.appspot.com',
    measurementId: 'G-73Q4PKGW40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFFIjuzqgfuxU_lQQRVglCf9wqCMrAX7I',
    appId: '1:853922079394:android:33acd9b17f4ef918b2edfb',
    messagingSenderId: '853922079394',
    projectId: 'chatly-861ab',
    storageBucket: 'chatly-861ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa51hcvgP9_QHPq4oe1fyVEtUp7P2oI6I',
    appId: '1:853922079394:ios:576aa1e6f8e8c97ab2edfb',
    messagingSenderId: '853922079394',
    projectId: 'chatly-861ab',
    storageBucket: 'chatly-861ab.appspot.com',
    iosBundleId: 'com.example.chatly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa51hcvgP9_QHPq4oe1fyVEtUp7P2oI6I',
    appId: '1:853922079394:ios:16376c5af76c17f2b2edfb',
    messagingSenderId: '853922079394',
    projectId: 'chatly-861ab',
    storageBucket: 'chatly-861ab.appspot.com',
    iosBundleId: 'com.example.chatly.RunnerTests',
  );
}
